[build]
  command = "yarn build" # the command you run to build this file
  functions = "built-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "_site" # create-react-app builds to this folder, Netlify should serve all these files statically

[[redirects]]
  from = "/counter"
  to = "/.netlify/functions/counter"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/salvations"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/salvations"